Parameters:
  InstanceName1:
    Description: EC2 Instance Name
    Type: String
  InstanceName2:
    Description: EC2 Instance Name
    Type: String
Resources:
  Ec2Instance1:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: udacity
      ImageId: 'ami-09e67e426f25ce0d7'
      InstanceType: t2.micro
      Tags:
        - Key: name
          Value: !Ref InstanceName1
  Ec2Instance2:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: udacity
      ImageId: 'ami-09e67e426f25ce0d7'
      InstanceType: t2.micro
      Tags:
        - Key: name
          Value: !Ref InstanceName2
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '9090'
          ToPort: '9090'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '9100'
          ToPort: '9100'
          CidrIp: 0.0.0.0/0
