version: 2.1
jobs:
  # deploy:
  #   docker:
  #     - image: amazon/aws-cli
  #   steps:
  #     - checkout
  #     - run:
  #         name: Ensure backend infrastructure exist
  #         command: |
  #           aws cloudformation deploy \
  #             --template-file template.yml \
  #             --stack-name my-stack
  verify:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: smoke test
          command: sh smoketest.sh
workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - verify