version: 2.1
commands:
  destroy_environment:
    steps:
      - run:
          name: desktroy when failing erros
          command: echo "erros happends failed"
          when: on_fail

jobs:
  build:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: deploy s3
          command: aws cloudformation deploy \
                  --template-file bucket.yml \
                  --stack-name "${CIRCLE_WORKFLOW_ID:0:7}" \
                  --parameter-overrides PipelineID="${CIRCLE_WORKFLOW_ID:0:7}"

  verify:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run: apk add --update curl
      - run:
          name: smoke test1
          command: sh smoketest.sh
      - run:
          name: echo
          command: echo ${CIRCLE_WORKFLOW_ID}
      - destroy_environment


workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build
      - verify