version: 2.1
commands:
  destroy_environment:
    steps:
      - run:
          name: desktroy when failing erros
          command: echo "erros happends failed"
          when: on_fail

jobs:
  verify:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run: apk add --update curl
      - run:
          name: smoke test1
          command: sh smoketest.sh
      - run:
          name: simulate error
          command: ssss
      - destroy_environment
        


workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - verify