version: 2.1
commands:
  destroy_environment:
    steps:
      - run:
          name: desktroy when failing erros
          command: echo "erros happends failed"
          when: on_fail

jobs:
  build:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: deploy promethus ec2
          command: aws cloudformation deploy
                  --template-file ec2.yml
                  --stack-name "stack-name-${CIRCLE_WORKFLOW_ID:0:7}"
                  --parameter-overrides file://parameters.json
                  # --parameter-overrides PipelineID="${CIRCLE_WORKFLOW_ID:0:7}"

  verify:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run: apk add --update curl
      - run:
          name: smoke test1
          command: sh smoketest.sh
      - run:
          name: echo
          command: echo ${CIRCLE_WORKFLOW_ID}
      - destroy_environment
  
  clean:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: 
          name: clean up aws ec2
          command: aws cloudformation delete-stack --stack-name $(aws cloudformation list-stacks --query "StackSummaries[?StackStatus=='CREATE_COMPLETE'].[StackName]" --outputaws cloudformation delete-stack --stack-name $(aws cloudformation list-stacks --query "StackSummaries[?StackStatus=='CREATE_COMPLETE'].[StackName]" --output text) text)

workflows:
  version: 2
  build_CI_CD:
    jobs:
      - build
      # - clean
      # - verify